Итоговый_проект/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='homepage'),
    path('profile/<str:username>/', views.profile, name='profile'),
    # Редактирование профиля
    path('profile/<int:id>/edit', views.edit_profile, name='edit_profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # разделы меню
    path('design/', views.design_page, name='design_page'),
    path('web_dev/', views.web_dev_page, name='web_dev'),
    path('mob_dev/', views.mob_dev_page, name='mob_dev'),
    path('marketing/', views.market_page, name='market'),
    # Новый пост
    path('new/', views.new_post, name='new_post'),
    # Черновик
    path('draft_post/', views.draft_new_post, name='draft_post'),
    # Черновики пользователя
    path('draft_arcticle/<str:username>/',
         views.draft_article, name='draft_article'),
    # Редактирование черновика
    path('posts/<int:post_id>/post_edit/',
         views.edit_draft_article, name='draft_edit'),
    # удаление черновика
    path('post/delete/<int:post_id>/',
         views.hide_draft, name='draft_hide'),
    # редактирование поста
    path('posts/<int:post_id>/post_edit/',
         views.post_edit, name='post_edit'),
    # удаление поста
    path('posts/delete/<int:post_id>/',
         views.hide_post, name='post_hide'),
    # комментарии
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    # лайки
    path('posts/<int:post_id>/like/', views.like_dislike, name="post_like"),
    path('posts/<int:post_id>/<int:comment_id>/like/',
         views.like_to_comment, name="comment_like"),
    # поиск
    path('search/', views.search_page, name="search"),
    # выборка по релевантности
    # path('search/req/', views.search_relevant, name="search_rel"),
]

Итоговый_проект/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

Итоговый_проект/Итоговый_проект/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]
    
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Итоговый_проект/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    username = models.CharField(
        max_length=25, verbose_name="ник пользователя", unique=True)
    first_name = models.CharField(max_length=15, verbose_name="Имя")
    last_name = models.CharField(max_length=20, verbose_name="Фамилия")
    email = models.EmailField(max_length=30, verbose_name="Почта", unique=True)
    img = models.ImageField(upload_to='images/',
                            verbose_name="Загрузить картинку", blank=True, default='images/avatardefault.jpeg')
    age = models.IntegerField(verbose_name='Возраст', blank=True, null=True)
    description = models.TextField(
        max_length=300, verbose_name='Краткое описание', blank=True)

    def get_full_name(self):
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

Итоговый_проект/users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import User


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class UserForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):

        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', 'age', 'img', 'description')


class UpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name',
                  'email', 'age', 'img', 'description']

Итоговый_проект/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy


from .forms import UserForm


class SignUp(CreateView):
    form_class = UserForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

Итоговый_проект/users/templates/users/includes/base.html
{% for post in posts %}
<div class="block">
    <ul class="post_bar">
        <li>
            Автор {{ post.author.get_full_name }}
        </li>
        <li>
            {{ post.pub_date|date:"d.m.Y" }}
        </li>
    </ul>
    <h3>{{ post.header }}</h3>
    <p>{{ post.text }}</p>
    <img src="{{ post.img }}" alt="">
    {% if not forloop.last %}
    <hr>{% endif %}
    {% endfor %}
</div>

Итоговый_проект/users/templates/users/includes/header.html
{% load static %}
<div class="top">
    <div class="logo">
        <h1><a href="{% url 'homepage' %}">Хабр</a></h1>
    </div>
</div>
<div class="All_header_nav">
    <div class="navbar">
        <ul>
            <li><a href="{% url 'design_page' %}">Дизайн</a></li>
            <li><a href="{% url 'web_dev' %}">Веб-разработка</a></li>
            <li><a href="{% url 'mob_dev' %}">Мобильная разработка</a></li>
            <li><a href="{% url 'market' %}">Маркетинг</a></li>
        </ul>
    </div>
    <div class="profile-logo">
        {% if user.is_authenticated %}
        <a href="{% url 'new_post' %}">Добавить статью</a>
        {% endif %}
        <a class="img_search" href="#"><img src="{% static 'img/free-icon-search-3991270.png' %}" alt="Поиск"></a>
        <div class="dropdown"><a href="#"><img src="{% static 'img/user-interface.png' %}" alt="Личный кабинет"></a>
            {% include './menu.html' %}
        </div>
        </a>
    </div>
</div>

Итоговый_проект/users/templates/users/includes/menu.html
{% if user.is_authenticated %}
<ul class="menu">
    <li><a href="{% url 'profile' request.user %}">Профиль</a></li>
    <li><a href="{% url 'logout' %}">Выйти</a></li>
</ul>
{% else %}
<ul class="menu">
    <li style='list-style-type: none'><a href="{% url 'login' %}">Войти</a></li>
    <li><a href="{% url 'users:signup' %}">Зарегистрироваться</a></li>
</ul>
{% endif %}